//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteChuyenDe1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class dbnewEntities1 : DbContext
    {
        public dbnewEntities1()
            : base("name=dbnewEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AdminAccount> AdminAccounts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

        public virtual ObjectResult<curdProduct_Result> curdProduct(Nullable<int> id, Nullable<int> cateid, string ma, string ten, string anh, Nullable<decimal> gia, string mota, string option)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));

            var cateidParameter = cateid.HasValue ?
                new ObjectParameter("cateid", cateid) :
                new ObjectParameter("cateid", typeof(int));

            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));

            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));

            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(string));

            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(decimal));

            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));

            var optionParameter = option != null ?
                new ObjectParameter("option", option) :
                new ObjectParameter("option", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<curdProduct_Result>("curdProduct", idParameter, cateidParameter, maParameter, tenParameter, anhParameter, giaParameter, motaParameter, optionParameter);
        }

        public virtual int CustomerAdd(string fullName, string email, string password, ObjectParameter customerID)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));

            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));

            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CustomerAdd", fullNameParameter, emailParameter, passwordParameter, customerID);
        }

        public virtual ObjectResult<GetCategories_Result> GetCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategories_Result>("GetCategories");
        }

        public virtual ObjectResult<GetProducts_Result> GetProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProducts_Result>("GetProducts");
        }

        public virtual ObjectResult<ProductsByCategory_Result> ProductsByCategory(Nullable<int> catergoryID)
        {
            var catergoryIDParameter = catergoryID.HasValue ?
                new ObjectParameter("CatergoryID", catergoryID) :
                new ObjectParameter("CatergoryID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductsByCategory_Result>("ProductsByCategory", catergoryIDParameter);
        }

        public virtual int ShoppingCartAddItem(Nullable<int> cartID, Nullable<int> productID, Nullable<int> quantity, Nullable<int> customerID)
        {
            var cartIDParameter = cartID.HasValue ?
                new ObjectParameter("CartID", cartID) :
                new ObjectParameter("CartID", typeof(int));
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));

            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));

            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ShoppingCartAddItem", cartIDParameter, productIDParameter, quantityParameter, customerIDParameter);
        }

        public virtual ObjectResult<showproduct_Result> showproduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showproduct_Result>("showproduct");
        }

        public virtual int OrderAdd(Nullable<int> customerID, Nullable<System.DateTime> orderDate, Nullable<System.DateTime> shipDate, Nullable<bool> status, Nullable<int> orderID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));

            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(System.DateTime));

            var shipDateParameter = shipDate.HasValue ?
                new ObjectParameter("ShipDate", shipDate) :
                new ObjectParameter("ShipDate", typeof(System.DateTime));

            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
            var orderIDParameter = orderID.HasValue ?
               new ObjectParameter("OrderID", orderID) :
               new ObjectParameter("OrderID", typeof(int));
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OrderAdd", customerIDParameter, orderDateParameter, shipDateParameter, statusParameter, orderIDParameter);
        }

        public virtual int ShoppingCartRemoveItem(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ShoppingCartRemoveItem", customerIDParameter);
        }

        public virtual ObjectResult<OrderList_Result> OrderList(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderList_Result>("OrderList", customerIDParameter);
        }

        public virtual ObjectResult<TopProduct_Result> TopProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopProduct_Result>("TopProduct");
        }

        public System.Data.Entity.DbSet<WebsiteChuyenDe1.Models.TopProduct_Result> TopProduct_Result { get; set; }

        public System.Data.Entity.DbSet<WebsiteChuyenDe1.Models.OrderList_Result> OrderList_Result { get; set; }
        public virtual ObjectResult<OrderListbycustomer_Result> OrderListbycustomer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderListbycustomer_Result>("OrderListbycustomer");
        }

        public System.Data.Entity.DbSet<WebsiteChuyenDe1.Models.OrderListbycustomer_Result> OrderListbycustomer_Result { get; set; }

        public System.Data.Entity.DbSet<WebsiteChuyenDe1.Models.sellerBest> sellerBests { get; set; }

        public System.Data.Entity.DbSet<WebsiteChuyenDe1.Models.GoiYSP> GoiYSPs { get; set; }
    }
}
